### ISSUE TITLE
composer.lock einchecken

### ISSUE THREAD

**Issue by 0x8DEADF00D** [elitepvpers-community/elite-cloud#14]
https://getcomposer.org/doc/01-basic-usage.md

> Commit your application's composer.lock (along with composer.json) into version control.
> This is important because the install command checks if a lock file is present, and if it is, it downloads the versions specified there (regardless of what composer.json says).

**Comment by Shawak** [comment]
https://github.com/elitepvpers-community/elite-cloud/commit/a0d1d8320fe3d136634e897ef7f46c966f75055f
