### ISSUE TITLE
Hauptseite erstellen

### ISSUE THREAD

**Issue by 0x8DEADF00D** [elitepvpers-community/elite-cloud#6]
- Sichtbar wenn man eingeloggt ist
- Menü:
  - Account
  - Userskripte
    - Alle Userskripte
    - Neues Userskript
    - Meine Userskripte
  - Administration (Auflisten von Accounts, Benutzergruppen mit Berechtigungen vergeben)

**Comment by Shawak** [comment]
Man könnte auf die Hauptseite auch später sowas wie eine Art Statistik einbauen mit Aufrufe pro Tag/Woche/Monat und Anzahl der User/Userscripte usw. um die Seite etwas auszufüllen.
